### ISSUE TITLE
Error when giving any other URL for tails-server

### ISSUE THREAD

**Issue by ankitkr1606** [bcgov/indy-tails-server#15]
When I'm trying to run the tails server with host as 0.0.0.0 and port 6543 it's working fine but whenever I'm giving an IP different from 0.0.0.0 Its giving me this error 
![tails-error](https://user-images.githubusercontent.com/25309320/102974425-86f0cf80-4524-11eb-8621-b873212a9de1.png)

**Comment by WadeBarnes** [comment]
How are you configuring the "different IP"?

The tails-server is running in a docker container.  It appears your telling it to bind to an IP that the container can't reach.  It needs to be listening on the IP address(es) of the container.  The ports from the container are then forwarded to the host machine, which is where you would expose the services on a separate IP/hostname.

**Comment by ankitkr1606** [comment]
Yeah, I just noticed that I made a mistake in that, Now I know where I was doing mistake. Thanks @WadeBarnes 
I'm closing this issue :)
