### ISSUE TITLE
Publish a docker image?

### ISSUE THREAD

**Issue by dbluhm** [bcgov/indy-tails-server#29]
Is there a published image of this tails server somewhere? If not, have we considered publishing one? We've been using one that I've unofficially pushed to hub.docker.com but the process is not automated and so can get out of sync when there are updates here.

**Comment by WadeBarnes** [comment]
There is no published images for this tails server.  Do you think it better to publish the image to project via `ghcr.io` or to dockerhub?

GHA examples for reference:
- `von-network`; the image is built and published to the project's `ghcr.io` repo which each push.
  - https://github.com/bcgov/von-network/blob/main/.github/workflows/build-docker.yml
- `BCDevOps/docker-weasyprint`; the image is build and pushed to Dockerhub when a release is cut.
  - https://github.com/BCDevOps/docker-weasyprint/blob/main/.github/workflows/publish.yaml

My initial thoughts are to publish it to the project's `ghcr.io` repo when releases are cut.

**Comment by dbluhm** [comment]
ghcr.io sounds great to me from a developer perspective. Can't say I'm well versed in whether that has implications on deploy though.

**Comment by WadeBarnes** [comment]
Ok, we'll start there.  I'll have a look at this shortly.

**Comment by WadeBarnes** [comment]
@dbluhm, Have a look at the PR; https://github.com/bcgov/indy-tails-server/pull/30

**Comment by WadeBarnes** [comment]
Once merged, I can cut a release here.  I'm thinking a `1.0.0` release.  Thoughts?

**Comment by dbluhm** [comment]
#30 looks good to me. I'm in agreement on a `1.0.0` release. This project is stable and the interface exposed is even more stable. I'm also aware of production deployments making use of it so `1.0.0` feels appropriate.

**Comment by WadeBarnes** [comment]
PR merged, [v1.0.0](https://github.com/bcgov/indy-tails-server/releases/tag/v1.0.0) release cut, and image published; https://github.com/bcgov/indy-tails-server/pkgs/container/tails-server
