### ISSUE TITLE
Unable to run the tailsserver in docker

### ISSUE THREAD

**Issue by abhimin** [bcgov/indy-tails-server#41]
I spin up von-network and trying to set up tailsserver using the bcgov/indy-tails-server repo but I'm getting error with aiohttp error.
Please confirm if the python versions and requirements.txt has valid versions.

**Comment by WadeBarnes** [comment]
Closing this as the developer reported being able to build and run the project here; https://github.com/bcgov/indy-tails-server/issues/43#issuecomment-1307281709

**Comment by abhimin** [comment]
Able to set up tailsserver in local
