### ISSUE TITLE
Ngrok auth token required for local Docker use

### ISSUE THREAD

**Issue by loneil** [bcgov/indy-tails-server#58]
As of recently, this project doesn't seem to want to start up with out an Ngrok Auth Token.

If following the readme instructions and running `manage start`, the docker-ngrok-tails-server container will fail to start up with:
![image](https://github.com/bcgov/indy-tails-server/assets/17445138/7dc2d10f-5230-43ee-99e2-eced7e40a11f)

Add the docker compose env needed and instructions for developers to set this up.

**Comment by esune** [comment]
Resolved by #59
