### ISSUE TITLE
Test in curl

### ISSUE THREAD

**Issue by guilherme-funchal** [bcgov/indy-tails-server#7]
Hello, I'm from Brazil and I am working as a collaborator on the Ian Constanzo project @ianco https://github.com/guilherme-funchal/django-aries-community. I'm trying to integrate Django with Indy-tails-server to save revocation registry from Aries and use ACA-PY.

1)I am trying to use the following python code:

<pre>
def upload_file(revocation_file, revo_reg_def):

    with open(revocation_file, 'rb') as tails_file:

        response = requests.put(
            PUBLIC_TAILS_URL + revo_reg_def,
            data = {"genesis": "http://172.17.0.1:9000/genesis", "tails": revocation_file}
        )
        response.raise_for_status()
        file_status = response
</pre>

2)Tails-server responds with 400 : 

<pre>
aries-django_1      | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://eb81e473004d.ngrok.io/JnkAjQLbFzx7TrcJWW1ACw:4:JnkAjQLbFzx7TrcJWW1ACw:3:CL:9:default:CL_ACCUM:595a72b2-2e3b-48da-9247-cb71303cd955
aries-django_1      | [30/Jul/2020 00:52:37] "POST /credential_offer/ HTTP/1.1" 500 85206
</pre>

3)I'm trying to use curl to test : 
<pre>
curl -X PUT -d tails=< revo_reg_def> http://<address-tails-server>

Error in tails-server :
2020-07-30 12:34:35,830 aiohttp.access INFO 172.19.0.2 [30/Jul/2020:12:34:35 +0000] "PUT /JnkAjQLbFzx7TrcJWW1ACw:4:JnkAjQLbFzx7TrcJWW1ACw:3:CL:49:default:CL_ACCUM:f455a85f-8e11-4574-a578-2ce5224ed6ee HTTP/1.1" 500 244 "-" "curl/7.68.0"
</pre>

@nrempel Can you help me ?

**Comment by ianco** [comment]
@guilherme-funchal some of the docs for running the aca-py demo are out of date.  If you run the tails server on your local, then run the aca-py demo using:

`LEDGER_URL=http://test.bcovrin.vonx.io ./run_demo faber --revocation --tails-server-base-url=https://9a2266924b71.ngrok.io`

(The ngrok server name will be different for you)

This gets passed to the aca-py agent here:

https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/runners/support/agent.py#L324

You can see the value just gets passed through to the aca-py agent.

I think aca-py will then create tails files as necessary, @nrempel can confirm ...

**Comment by guilherme-funchal** [comment]
Thanks for help @ianco, using the Faber/Alice demo  seems to work. 

Tomorrow I will try to see the steps  in Django version and compare it with the demo, I believe I am very close to making it work.

**Comment by esune** [comment]
@guilherme-funchal @ianco Is this still an open issue?

**Comment by guilherme-funchal** [comment]
Hello, I will close.

Thanks
